### PR TITLE
Updates with CMSSW_11_3_0_pre6, CMSSW_12_0_0_pre1

### PR DESCRIPTION
**Pull request by xoqhdgh1002**
Merged previous local data and new generated data

### CODE REVIEW

**Comment by jpata** [comment]
Thanks for the update. 

@slava77 I made the updated version available here: https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/index_pr11.html so we can check it before merging.

**Comment by jpata** [comment]
Regarding TimeDiff, I think I'm confused.

```
CMSSW_11_3_0_pre6, step3: [TimeDiff]preview: 83.653 s/ev ==> 86.1739 s/ev
CMSSW_12_0_0_pre1, step3: [TimeDiff]preview: 78.0377 s/ev ==> 83.653 s/ev 
```

Is the format `NEW ==> OLD`? I thought in the past it was `OLD ==> NEW`. Thanks in advance for the clarification @xoqhdgh1002 !

**Comment by slava77** [comment]
> Is the format `NEW ==> OLD`? I thought in the past it was `OLD ==> NEW`.

yes, I'm pretty sure the arrow pointed to new from old.

**Comment by slava77** [comment]
`Bongho` is not a good way to name a PR; please use the `Edit` button at the top of the page and change to a more descriptive title

**Comment by slava77** [comment]
> @slava77 I made the updated version available here: https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/index_pr11.html so we can check it before merging.

- http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/results/summary_plot_html/CMSSW_12_0_X_step3.html from `Summary of CMSSW_12_0_X(RECO_AOD) [Short Summary Time and Memory(AOD)]` still has only pre1 and does not yet include a few older releases. We talked about adding at least 11_3_0
- igprof results links to `txtLink` are broken, e.g. http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/results/RES/CMSSW_12_0_0_pre1_step3_mem1.res
- in the step4 piecharts please use a link pointing to packages  (`groups=packages`) http://cms-reco-profiling.web.cern.ch/cms-reco-profiling/circles/piechart.php?local=false&dataset=CMSSW_12_0_0_pre1%2Fslc7_amd64_gcc900%2F23434.21%2Fstep4_circles&resource=time_real&colours=default&groups=packages&threshold=0

**Comment by slava77** [comment]
> @slava77 I made the updated version available here: https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/index_pr11.html so we can check it before merging.

Perhaps it's still much more useful to update the page first and then apply the fixes.

**Comment by jpata** [comment]
Let's merge this PR here now, and prepare a follow-up with the necessary fixes as requested above.

**Comment by jpata** [comment]
This update is now live at https://cms-reco-profiling.web.cern.ch/cms-reco-profiling/.
@xoqhdgh1002 please open a follow-up PR to fix/clarify the issues brought up above.
Thanks!

**Pull request merged**
