### PR TITLE
update the scripts and web page for CMSSW_12_2_0,CMSSW_12_2_0_pre1,CMSSW_12_2_0_pre2,CMSSW_12_2_0_pre3

### PR DESCRIPTION
**Pull request by xoqhdgh1002**

### CODE REVIEW

**Comment by xoqhdgh1002** [comment]
All scripts are placed in `test/scripts`.
Additionally, CMSSW_12_3_0_pre4 is updated for web page.
Please check and comments

**Comment by jpata** [comment]
Thank you for the update.

- can you please remove the `.pyc` files from the commit?
- it looks like in index.html you changed the indentation (whitespace) style. This makes it hard to see the actual changes. Is it possible to revert to the old indentation?

**Comment by xoqhdgh1002** [comment]
Thank you for comments.
I've modified everything you commented.
Please check and comments.

**Comment by jpata** [comment]
I meant this as the whitespace change. Was it necessary, and if not, can it be reverted? It makes it hard to see what the actual changes in the html are.
Screenshot from 2022-01-28 12-02-59

**Comment by jpata** [comment]
kind ping on this

**Comment by xoqhdgh1002** [comment]
I'm sorry. I misunderstood about whitespace.
I uploaded web pace after correction.

**Comment by jpata** [comment]
Thanks for the update, but I think there is still some miscommunication.

If you check the changes proposed in this PR: https://github.com/jpata/cms-reco-profiling-web/pull/43/files#diff-8f62b6ced28d3396b501d2e89a2e7cb761d16cd7dc977aebece03d4a5da5c24e

the whole index.html changes. I would expect only changes at the end of the file, where the new releases are added. The rest of the file should not be changed. As it is now, the file has changes on almost every line, so I can't tell what really changed in detail.

Can you please check if it's possible to add the changes **for only the new releases** at the end of the file?

Thanks, and I hope that's clearer.

**Comment by xoqhdgh1002** [comment]
Thanks for the comments, but I deleted old source code. So it seems difficult to change back to original.

There are a few things that have changed with the new source code.
1. Memory RES link : Existing link wasn't connected and the res file was downloaded. So I changed extension `mem.1.res` -> `mem_1.res`.
2. Delete unconnected link : Some links to earlier versions of cmssw were on the web page despite the file missing. Those links have been deleted.

Next time, when updating to a new release, we will keep the previous version.

Thanks, and I hope I understand correctly.

**Comment by jpata** [comment]
Thank you, OK, if there were too many changes to the underlying scripts, then we merge it as it is.
In the future, it would be good to do small updates, so we can check the changes more easily.

**Pull request merged**
